# name: GitHub Dark
# author: lone
# upstream: https://github.com/primer/github-vscode-theme
$bg      = 0xff0d1117
$fg      = 0xffe6edf3
$accent  = 0xff58a6ff
$green   = 0xff3fb950
$red     = 0xffff7b72
$yellow  = 0xffd29922
$magenta = 0xffbc8cff
$cyan    = 0xff39c5cf

general {
    col.active_border = $accent $magenta $cyan $green 90deg
}
